### ISSUE TITLE
H2StreamMaxMemSize causes indefinitely open streams to hang

### ISSUE THREAD

**Issue by mpnewcomb** [icing/mod_h2#149] opened 2017-12-01 17:17 UTC
We are using [grpc web proxy](https://github.com/improbable-eng/grpc-web) to stream grpc services to clients. It uses http/2 streams to deliver data back and forth between the client and some java grpc services on the backend.

We have apache httpd in front acting as a reverse proxy and we are having trouble with apache caching streaming data until the stream is either closed or H2StreamMaxMemSize is reached.

My backend service writes a series of protocol buffers upon initial connection, then sends updates over the stream as users make changes to the system. We can trace all the data being sent and delivered properly until it gets to apache httpd. There it is held forever... my chrome request just sits in pending. We know it is because of H2StreamMaxMemSize, because we lowered that value to 1024 (the minimum), then I just looped over my data 100 times to be sure I sent at least 1024 bytes. Sure enough, my client was happy with streaming data coming in. Also, if I write the data I have and close the stream, it is also delivered as expected... but I don't want to close the stream!

There needs to be either a timeout on waiting or a similar tcp_nodelay type of setting where data is immediately delivered to the client when it receives data on the backend.

**Comment by icing** [comment] 2017-12-02 19:09
You are correct that mod_h2 buffers response data up to H2StreamMaxMemSize - unless a FLUSH bucket is written by the response creator. Then it writes the data immediately.

I have test setups with a python script that write a short line every second and test that directly and behind a mod_proxy setup. Usually, mod_proxy flushes intermediate data correctly, so something is different here.

Can you produce a log of such a stalled request at level trace2? As directive ```LogLevel http2:trace2``` should show what data arrives, if it FLUSHes or not. Thanks!

**Comment by mpnewcomb** [comment] 2017-12-03 02:10
Our config looks like:
 ProxyPass "h2://backend.example.com/"

I tried adding:
flushpackets=on
But it did not work.

The docs for flushpackets says:
Determines whether the proxy module will auto-flush the output brigade after each "chunk" of data. 'off' means that it will flush only when needed; 'on' means after each chunk is sent; and 'auto' means poll/wait for a period of time and flush if no input has been received for 'flushwait' milliseconds. Currently, this is in effect only for AJP.

That leads me to believe that each mod_proxy_xxx needs to implement it because I only saw references to it in the ajp and fcgi proxies...

I will get those logs for you on Monday, but the bottom line is that the h2 proxy should behave like described above.

Thanks!

**Comment by icing** [comment] 2017-12-03 09:10
Ah, you are using mod_proxy_http2. Somehow missed that. I assume h2 on front and h1 to backend works fine?

**Comment by mpnewcomb** [comment] 2017-12-04 14:38
We can't use h1 on the backend because grpc is only h2.

**Comment by icing** [comment] 2017-12-04 15:35
Tststs. Well, for debugging proxy_http2 I need additionally 

```
LogLevel proxy:debug
LogLevel proxy_http2:trace2
```
Thanks!

**Comment by mpnewcomb** [comment] 2017-12-04 19:42
Here is a log...
[grpc-ssl-error.log](https://github.com/icing/mod_h2/files/1528520/grpc-ssl-error.log)

**Comment by mpnewcomb** [comment] 2017-12-04 20:04
Also, even though the stream seems to stay open, it closes after 8.3 minutes (according to console on Chrome). That's suspiciously close to 500,000 ms...

The GRPC web client uses fetch and it seems to close with a net::ERR_CONNECTION_RESET after that time period... sorry, just throwing more problems out.

**Comment by icing** [comment] 2017-12-05 09:03
No need to feel sorry. As long as you do not expect me to solve this right away...

I might find time on the weekend to look into this.

**Comment by mpnewcomb** [comment] 2017-12-06 16:49
More information:
I removed apache httpd from proxying my grpc calls and everything works fine... just confirming that apache http does not proxy grpc http/2 streams well. linkerd and the grpc web proxy (which uses the go HTTP server) seem to work fine.

Old path:
chrome -> apache httpd -> grpcwebproxy -> linkerd -> grpc-java-service (hangs)
New path:
chrome -> grpcwebproxy -> linkerd -> grpc-java-service (works fine)

Also, my last comment about the 8.3 minutes and then getting my fetch() closed, is not due to apache httpd because it still happened after it was removed from the path.

**Comment by icing** [comment] 2017-12-09 16:57
Just to confirm: I see the request ```POST https://titan/svc/``` is scheduled, but never returns with a response. I assume that is the one, right?

I will see if I can reproduce that. If you have time, would be nice to get such a log with the log level for proxy set as well. See 5 messages above.

**Comment by icing** [comment] 2017-12-09 17:11
Ok, I need to log with

```
LogLevel http2:trace2
LogLevel proxy:debug
LogLevel proxy_http2:trace2
```
to see what is going wrong. I tried to reproduce locally with a proxies cgi that outputs a line every second that those go through the server without additional delay - as they should.

**Comment by icing** [comment] 2018-01-16 09:37
Is there still interest in this? Because without detailed logs, I'd have to close it.

**Comment by mpnewcomb** [comment] 2018-01-16 13:53
Those were the logs at those levels.

**Comment by icing** [comment] 2018-01-16 14:02
Sorry, but I do not see and ```proxy``` or ```proxy_http2``` entries in grpc-ssl-error.log. Did I miss something?

**Comment by mpnewcomb** [comment] 2018-01-16 15:42
Hmmm, they are both turned on in the httpd-vhosts.conf file.

I changed my mechanism to chunk the data and close the stream, but there will be no getting around this issue once I get my initial ui up and running.

I can repost, but the grpc proxy is just using the go http2 server, so not sure what it would be doing differently, but it stops cold at apache.

Close the issue if you must, I'll just reopen another one with more logs when I get to the part where I need a continuously open stream...

**Comment by icing** [comment] 2018-01-16 16:01
I am in no hurry to close things here. There definitely will be lots of logging from mod_proxy_http2 if requests come its way. Maybe there is a misspelling somewhere?

I leave this open until you find the opportunity to catch some traffic.

**Comment by icing** [comment] 2018-04-28 11:58
Closing due to timeout (but open another one if you have new data).

**Closed by icing** 2018-04-28 11:58 UTC
