### ISSUE TITLE
Upgraded Apache to HTTP/2 breaks SSE

### ISSUE THREAD

**Issue by johnfound** [icing/mod_h2#147] opened 2017-09-30 16:42 UTC
I have a small web application that runs on shared Apache hosting and uses FastCGI (mod_fcgi) and server-sent events (SSE).

In order to make SSE, we needed to set `FcgidOutputBufferSize=0` for the virtual host on the server. Because SSE protocol needs all events to be sent immediately, without buffering.

But after an upgrade of the server to Apache  v2.4.27 and the protocol to HTTP/2.0 the SSE stream stopped to be sent properly, but in big blocks with huge pauses between them, until enough events are collected to make big enough package.

It seems that switching to HTTP/2.0 activated some kind of buffering that delays the stream.

If I force my browser to use only HTTP/1.1 everything works as before.

The hosting provider claims he can't fix this problem, because it will need switching back to HTTP/1.1 and he is not willing to do so.

So, is it some fundamental incompatibility between SSE and HTTP/2.0? Or it is bug and I need only to wait for a fix? Or I am doing things wrong and there is a way to make Apache to send the `text/event-stream` without buffering?

Any work-around?

**Comment by icing** [comment] 2017-10-04 09:23
There is buffering done in the http2 layer, *but* these buffers are flushed when the sender tells it so. In Apache internals, there is a meta data bucket called FLUSH which triggers this.

I see in the mod_fcgid source that it also FLUSHes data when the buffer size is exceeded (which in your setting should be every time). If you can, a trace of such a stuck request with

```
LogLevel http2:trace3
```

would be fine. That lists the http2 internal buffering and will help me reproduce this. Thanks!

**Comment by johnfound** [comment] 2017-10-04 12:04
Well, unfortunately, this is my hosting provider servers and I don't have any access to the server configuration or control. I will try to open the support ticket again and to link the admins here if they have a good will to contribute.

**Comment by icing** [comment] 2017-10-04 12:09
I see. If you control the php side of things, could you verify that *after* the first 32 KB (or so) on the response, the data is sent out in a timely fashion? If the problem is only in the initial chunk, that would help me find the cause. Thx!

**Comment by johnfound** [comment] 2017-10-05 05:58
Meanwhile, I started a test script on the server. It is an event source that emits the sent byte count as SSE on every 100ms. One event is exactly 32 bytes (including CRLF): 

Check the difference between: 

    curl --http2 https://board.asm32.info/\!echo_events

and 

    curl --http1.1 https://board.asm32.info/\!echo_events

**Comment by icing** [comment] 2017-10-05 11:27
Hmm, thanks. I can see the effect. mod_http2 for some reason collects response data until it has reached its desired packet length - for some reason not clear to me. My tests with a python script behind a mod_cgid does behave correctly. Will need to test a mod_fcgid setup.

**Comment by johnfound** [comment] 2017-10-05 12:13
> Will need to test a mod_fcgid setup.
Isn't it the same for HTTP/1.1 and 2.0?

**Comment by johnfound** [comment] 2018-02-07 07:11
**Update:** The domain asm32.info has been moved to Nginx sever. This way, the above published test link ("!echo_events") works properly with HTTP1.1 and HTTP2, but this is not because of bug in Apache fixed.

**Comment by icing** [comment] 2018-02-07 09:33
Closing this as I am unable to reproduce and you unable provide logs. Seems we cannot move forward on this one.

**Closed by icing** 2018-02-07 09:33 UTC

**Comment by icing** [comment] 2018-02-09 09:07
FYI for anyone looking at this: there is [a patch proposed to backport into 2.4.x that affects mod_proxy_fcgi flushing behaviour](http://people.apache.org/~elukey/httpd_2.4.x-mod_proxy_fcgi-force_flush.patch). Not directly related, but close.
