### ISSUE TITLE
SNI and wildcard certificate problem

### ISSUE THREAD

**Issue by cfhay** [icing/mod_h2#34] opened 2015-07-16 11:27 UTC
I have the following apache config (using event MPM):

```
<VirtualHost 192.0.2.1:443>
    ServerName example.com
    ServerAlias *.example.com
    SSLEngine on
    [...]
</VirtualHost>
```

I have a valid wildcard certificate for the domain:
```
X509v3 Subject Alternative Name:
    DNS:*.example.com, DNS:example.com
```

I have two DNS entries, `a.example.com.` has an `A` record to `192.0.2.1`, and `b.example.com.` has a `CNAME` record to `a.example.com.`

When I open a site with Chrome with `https://a.example.com/`, everything works fine, `h2` connection is established to the server. But after when I try to open `https://b.example.com/`, apache returns a `400 Bad Request`, and a warning appears in the logfile:

```
AH02032: Hostname a.example.com provided via SNI and hostname b.example.com provided via HTTP are different
```

If I close Chrome, open it again, and open `https://b.example.com/`, that site works, but then `https://a.exmaple.com/` throws the same error, just with the hostnames swapped.

I guess it's because the SNI hostname was provided when the connection was made, and Chrome tries to reuse the existing connection because it maps to the same ip address and port pair. So the new request happened over the same TLS connection, but with a different Host header.

I don't know which is the best solution to solve this problem. Maybe Chrome should create a new connection for every hostname. Maybe apache should handle the request, if the certificate of the SNI and the http hostname would be the same. Dunno.

**Comment by cfhay** [comment] 2015-07-16 15:27
Noticed the patch https://raw.githubusercontent.com/icing/mod_h2/master/sandbox/httpd/patches/sni_misdirect.patch
I applied it, and it properly returns 421 instead of 400. But Chrome still doesn't want to create a new connection to the server. Is this a Chrome problem?

**Comment by icing** [comment] 2015-07-17 15:13
To the best of my knowledge, that sounds like a Chrome problem. Have you tried Firefox with the site setup? Would be good to know. Thanks!

**Comment by cfhay** [comment] 2015-07-17 15:36
Hm, same problem with Firefox. Tried with Firefox 39 (latest stable), 32bit, official, on a Windows 7 64bit.

**Comment by mcmanus** [comment] 2015-07-17 15:41
try it with firefox 41 (aurora) - it has a bug fix to 421 handling that might be relevant here. That fix has been uplifted to firefox 40 (beta) but I'm not sure if a new build containing it has been made yet.

**Comment by icing** [comment] 2015-07-17 15:42
Thanks for reaching out, Patrick.

**Comment by cfhay** [comment] 2015-07-18 06:51
Hm, still nope. Installed Firefox Developer Edition 64-bit, official (41.0a2 2015-07-17). Still getting 421 with server generated error message in a tab, no new connection is made.

**Comment by cfhay** [comment] 2015-07-18 06:55
Wait, I don't get it. Network tab shows 500 instead of 421 status code. I think this should be the problem in the first place. I'll check the patch now.

**Comment by cfhay** [comment] 2015-07-18 07:09
Apache logs show 421 status, browser receives 500 status... I don't get it...

**Comment by icing** [comment] 2015-07-18 09:02
Hmm, the patch for 421 support affects not only modules, but also apache core. i think there maybe the cause for the 500 when core tries to gen an error page. 

Any chance to reproduce with the sandbox server?

**Comment by cfhay** [comment] 2015-07-22 11:29
Before retrying with sandbox, raised log level to trace6, I got this (relevant snippet, using 0.8.1):

```
[...]
[Wed Jul 22 13:21:00.606945 2015] [http:trace3] [pid 1326:tid 139780633360128] http_filters.c(1006): [client 127.0.0.1:38570] Response sent with status 421, headers:
[Wed Jul 22 13:21:00.606958 2015] [http:trace5] [pid 1326:tid 139780633360128] http_filters.c(1013): [client 127.0.0.1:38570]   Date: Wed, 22 Jul 2015 11:21:00 GMT
[Wed Jul 22 13:21:00.606966 2015] [http:trace5] [pid 1326:tid 139780633360128] http_filters.c(1016): [client 127.0.0.1:38570]   Server: Apache
[Wed Jul 22 13:21:00.606985 2015] [http:trace4] [pid 1326:tid 139780633360128] http_filters.c(835): [client 127.0.0.1:38570]   Content-Length: 331
[Wed Jul 22 13:21:00.606995 2015] [http:trace4] [pid 1326:tid 139780633360128] http_filters.c(835): [client 127.0.0.1:38570]   Content-Type: text/html; charset=iso-8859-1
[Wed Jul 22 13:21:00.607004 2015] [h2:debug] [pid 1326:tid 139780633360128] h2_task_output.c(75): [client 127.0.0.1:38570] h2_task_output(0-3): write without response for GET lo.loginet.hu /
[Wed Jul 22 13:21:00.607018 2015] [h2:trace1] [pid 1326:tid 139780633360128] h2_task_output.c(121): (103)Software caused connection abort: [client 127.0.0.1:38570] h2_task_output(0-3): opened and passed brigade
[Wed Jul 22 13:21:00.607033 2015] [h2:trace1] [pid 1326:tid 139780633360128] h2_task_output.c(125): [client 127.0.0.1:38570] h2_task_output(0-3): write brigade
[Wed Jul 22 13:21:00.607085 2015] [h2:trace1] [pid 1326:tid 139780633360128] h2_task.c(256): [remote 127.0.0.1:38570] h2_task(0-3): processing done
[Wed Jul 22 13:21:00.607101 2015] [h2:trace2] [pid 1326:tid 139780633360128] h2_mplx.c(307): [client 127.0.0.1:38570] h2_mplx(0): task(3) done
[Wed Jul 22 13:21:00.607201 2015] [h2:trace2] [pid 1326:tid 139780440327936] h2_mplx.c(699): [client 127.0.0.1:38570] h2_mplx(0): trywait on data for 0.010000 ms)
[Wed Jul 22 13:21:00.607220 2015] [h2:trace2] [pid 1326:tid 139780440327936] h2_conn_io.c(130): [client 127.0.0.1:38570] h2_conn_io: try read, block=1
[Wed Jul 22 13:21:00.607233 2015] [core:trace6] [pid 1326:tid 139780440327936] core_filters.c(526): [client 127.0.0.1:38570] core_output_filter: flushing because of FLUSH bucket
[Wed Jul 22 13:21:00.607277 2015] [ssl:trace4] [pid 1326:tid 139780440327936] ssl_engine_io.c(2088): [client 127.0.0.1:38570] OpenSSL: read 5/5 bytes from BIO#7f2114006630 [mem: 7f2114031163] (BIO dump follows)
[Wed Jul 22 13:21:00.607293 2015] [core:trace6] [pid 1326:tid 139780440327936] core_filters.c(526): [client 127.0.0.1:38570] core_output_filter: flushing because of FLUSH bucket
[Wed Jul 22 13:21:00.607303 2015] [ssl:trace4] [pid 1326:tid 139780440327936] ssl_engine_io.c(2088): [client 127.0.0.1:38570] OpenSSL: read 41/41 bytes from BIO#7f2114006630 [mem: 7f2114031168] (BIO dump follows)
[Wed Jul 22 13:21:00.607322 2015] [h2:trace2] [pid 1326:tid 139780440327936] h2_conn_io.c(99): [client 127.0.0.1:38570] h2_conn_io(0): read 17 bytes:  0  0  8  6  0  0  0  0  0.
[Wed Jul 22 13:21:00.607337 2015] [h2:trace1] [pid 1326:tid 139780440327936] h2_session.c(314): [client 127.0.0.1:38570] h2_session(0): on_frame_rcv #6, type=6
[Wed Jul 22 13:21:00.607346 2015] [h2:trace2] [pid 1326:tid 139780440327936] h2_session.c(373): [client 127.0.0.1:38570] h2_session: on_frame_rcv PING[length=8, ack=0, stream=0]
[Wed Jul 22 13:21:00.607358 2015] [h2:debug] [pid 1326:tid 139780440327936] h2_session.c(186): [client 127.0.0.1:38570] h2_session(0): before_frame_send PING[length=8, ack=1, stream=0]
[Wed Jul 22 13:21:00.607368 2015] [h2:trace1] [pid 1326:tid 139780440327936] h2_conn_io.c(215): [client 127.0.0.1:38570] h2_conn_io: buffering 17 bytes
[Wed Jul 22 13:21:00.607375 2015] [h2:trace2] [pid 1326:tid 139780440327936] h2_session.c(198): [client 127.0.0.1:38570] h2_session(0): on_frame_send
[Wed Jul 22 13:21:00.607388 2015] [h2:trace1] [pid 1326:tid 139780440327936] h2_session.c(1054): [client 127.0.0.1:38570] h2_stream(0-3): submitting response 500
```

So, at http_filters.c, line 1006 the status is 421, but at h2_session.c, line 1054 the status is 500. Somewhere between the status changes.

**Comment by cfhay** [comment] 2015-07-22 13:38
Tried with sandbox build. Issued `make` in `sandbox/httpd`, enabled `httpd-ssl.conf`, `mod_ssl`, `mod_shmcb`, built `mod_h2` from git master, added that too, added `H2Engine`, `H2Direct`, `H2HackMpmEvent`, and changed `SSLCipherSuite` in `httpd-ssl.conf` to include `GCM` ciphers first. The webserver still thinks it sends 421, but the browser receives 500.

**Comment by icing** [comment] 2015-07-22 14:10
Ok, have an idea. Does the problem go away when "H2SerializeHeaders on" is commented out?

**Comment by icing** [comment] 2015-07-22 14:51
Please try the v0.8.2 release. Thanks!

**Comment by cfhay** [comment] 2015-07-22 15:27
Thank you. Well, this fixed the problem for the local test apache, but not with an another one with a slightly different config, I'll bisect the differences and will tell what difference causes the breakage.

**Comment by cfhay** [comment] 2015-07-22 16:00
I don't get it, now I restarted the local apache (with same config), and I get 500 again. Can this be some kind of race condition due to threading?

**Comment by cfhay** [comment] 2015-07-22 20:00
I deleted my previous comments. The server returns 421 now, always. Thank you (Just Chrome doesn't handle the 421 properly)

**Closed** 2015-07-22 20:29 UTC

**Comment by cfhay** [comment] 2015-07-22 20:41
Two notes:

421 handling is an optional feature by the rfc:

```
9.1.2
[...]
Clients receiving a 421 (Misdirected Request) response from a server MAY retry the request
[...]
```

Also, in Firefox's case, this causes a suboptimal state, as when it receives a 421 code, it will close the other connection. So if a webpage contains many URLs with two hosts on the same ip/port pair, many terminated and reopened connections will occur, which is actually worse than having two HTTP/1.1 connections with keep-alive, which defets the purpose of HTTP/2. (Well, this is also more like a problem at Firefox's side, as it should just simply open two connections in parallel)

I think in the long term handling the request would be better (if the would be served certificate is the same as the presented one at connection start), than denying it with 421.
