### ISSUE TITLE
PHP session module fails when using HTTP/2

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_h2#47] opened 2015-09-02 15:08 UTC
Environment: FreeBSD 10.2, Apache 2.4 (with Protocols patch), LibreSSL 2.2.3

When I switch apache to mod_h2, existing sessions can still be reused.
Creating new sessions when mod_h2 is enabled fails. For e.g. roundcube I can see
```
Successful login for bernard (ID: X) from 192.2.0.176 in session xxxxxxxxx
Aborted session yyyyyyy; no valid session data found
```
Could it be the multiplexing? session-id's are ***not*** matching

**Comment by icing** [comment] 2015-09-02 15:13
Is HTTP/2 used then or is the module just loaded?

Also, when do new session fail? The login works, but the next requests does not recognize the session and goes back to login? Or is the login failiing right away?

**Comment by JBlond** [comment] 2015-09-04 08:11
on Windows with PHP over fcgid I did not have that problem. But it might be that it is different since PHP runs more or less separated to apache.

**Comment by icing** [comment] 2015-09-04 08:12
Sp1l, what config are you using regarding php inside Apache? Myself not an expert on this, but there are several possibilities afaik,

**Comment by Sp1l** [comment] 2015-09-04 11:10
Sorry for the delay. Trying to figure it out.

In Chromium (Iron, Opera) my server seems to not do h2 at all (HTTP/2 and SPDY indicator)
In Firefox, the add-on shows "HTTP/2 is active for the top-level document" and any app using sessions (login) was failing the login.

h2test.org reports "No support for HTTP/2 was found."
spdycheck.org reports "Missing NPN Extension in SSL/TLS Handshake"

vhost config
<IfModule h2_module>
H2SerializeHeaders on
H2Direct on
</IfModule>

**Comment by icing** [comment] 2015-09-04 11:18
Ok, chrome should connect. Let's see what is going on here...

If you have the latest core-protocools (v0.9.6 or later) applied, force proper h2 selection by

```
    Protocols h2 http/1.1
    ProtocolsHonorOrder on
```

Then, if you have a nghttp binary somewhere (from sandbox or somewhere else), try a GET with that one. It only speaks HTTP/2, so any failure to select that will immediately give an error.

Second, if you have a `curl` with `--http2` (maybe from sandbox), you can do

```
    curl -kv --http2 https://<yourserver>/index.html
```
and should see in the debug output from curl something like 

```
* ALPN, server accepted to use h2
```

When we have that all working, we can look at php without other weird things getting in our way.

**Comment by Sp1l** [comment] 2015-09-05 08:56
Updated to mod_h2 0.9.7 and still see the same behaviour. Output of curl --http2 doesn't show ALPN nor NPN.

Testing with curl for e.g. twitter.com shows
```
* NPN, negotiated HTTP2 (h2)
```
curl was built with ALPN support, I'll check to see what goes on there.

**Comment by Sp1l** [comment] 2015-09-05 10:05
## General
At least I've solved the curl mistery... The FreeBSD LibreSSL port patches the OpenSSL version number from 0x20000000L to 0x1000107fL (version at time of forking). With this patch removed curl does properly use ALPN.
```
# curl -kv --http2 https://twitter.com
* ALPN, offering h2
* ALPN, offering http/1.1
# curl -kv --http2 https://<yourserver>
* ALPN, offering h2
* ALPN, offering http/1.1
...
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
```
So (with the added Protocol and ProtocolHonorOrder On directives) my server does negotiate http2 correctly. chrome://net-internals now also shows proper h2 transports.

## Session / Cookies
Still some weirdness going on with cookies and/or sessions.
After loading the RoundCube login page I have a cookie
`cookie:roundcube_sessid=hfgk...etc...`
When POSTing the username/password with that cookie the response sets another cookie with a *different* sessid
`set-cookie:roundcube_sessauth=-del-; expires=Sat, 05-Sep-2015 09:43:32 GMT; Max-Age=-60; path=/; secure; httponly, roundcube_sessid=c4h6...etc...; path=/; secure; HttpOnly, roundcube_sessauth=S9f3...etc..; path=/; secure; httponly`
and returns a 302 `location:./?_task=mail`
Requesting that resource it uses the *original* sessid
`cookie:roundcube_sessid=hfgk...etc...`
and notably not the roundcube_sessauth token which is bound to fail.

Decided to try my RainLoop webmail installation as well and it behaves slightly different.
`set-cookie:rltoken=4118...etc...; expires=Mon, 05-Oct-2015 09:59:16 GMT; Max-Age=2592000; path=/; httponly`
Any next POST just sends `cookie:rlsmauth=deleted;rltoken=4118...etc...` with a correct body and returns an error "Invalid token"

**Comment by icing** [comment] 2016-01-12 15:05
Closing, cannot reproduce.

**Closed by icing** 2016-01-12 15:05 UTC
